export const data = [
  {
    name: 'Olivia',
    email: 'example13@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Data analyst',
    avatar: '/avatars/1.png',
    displayName: 'Olivia',
  },
  {
    name: 'Benjamin',
    email: 'example1@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Not Avialiable now',
    avatar: '/avatars/2.png',
    displayName: 'Benjamin',
  },
  {
    name: 'Emma',
    email: 'example2@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'your design plug',
    avatar: '/avatars/3.png',
    displayName: 'Emma',
  },
  {
    name: 'Henry',
    email: 'example3@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Whats app only',
    avatar: '/avatars/4.png',
    displayName: 'Henry',
  },
  {
    name: 'Charlotte ',
    email: 'example4@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Available',
    avatar: '/avatars/5.png',
    displayName: 'Charlotte ',
  },
  {
    name: 'Samuel',
    email: 'example5@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Always do good .GOD DID!!!',
    avatar: '/avatars/6.png',
    displayName: 'Samuel',
  },
  {
    name: 'Amelia',
    email: 'example6@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Only God is geatest',
    avatar: '/avatars/7.png',
    displayName: 'Amelia',
  },
  {
    name: 'Gabriel',
    email: 'example7@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Medical and Health Education',
    avatar: '/avatars/8.png',
    displayName: 'Gabriel',
  },
  {
    name: 'Lily',
    email: 'example8@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Specially Graced',
    avatar: '/avatars/9.png',
    displayName: 'Lily',
  },
  {
    name: 'Jameson ',
    email: 'example9@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Specially Graced',
    avatar: '/avatars/9.png',
    displayName: 'Jameson ',
  },
  {
    name: 'Noah ',
    email: 'example11@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Specially Graced',
    avatar: '/avatars/9.png',
    displayName: 'Noah',
  },
  {
    name: 'Caleb  ',
    email: 'example12@gmail.com',
    newUser: true,
    availability: false,
    image: '',
    about: 'Specially Graced',
    avatar: '/avatars/9.png',
    displayName: 'Caleb  ',
  },
];
